name: Publish to pub.dev
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      # - name: Run tests
      #   run: flutter test
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.TOKEN }}
          flutter_package: true
          skip_test: true
          dry_run: true
